# Site settings
name: oZone.network
title: oZone.network
email: pliablepixels@gmail.com
description: "Making ZoneMinder awesome"
baseurl: ""
url: "http://ozone.network"
disqusid: zmNinja

# Build settings
markdown: kramdown
permalinks: pretty
